spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: zzandi.dev@gmail.com
    password: mzsbxaueqvjjrpoi
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

