spring:
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/zzandi
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path : /h2-console

  mail:
    host: smtp.gmail.com
    port: 587
    username: zzandi.dev@gmail.com
    password: mzsbxaueqvjjrpoi
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# 로그로 하이버네이트 실행 SQL 출력!
# 프로젝트 실행 할 때 실행되는 쿼리문 보여주는 설정입니다.
logging.level:
  org.hibernate.SQL: debug